### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-9-practica-de-arquitectura-buscadores-de-datos#1]
* Roldan Uriel Arcadio Ávila
* Pedro Garcia Garcia
* Ariadna Monserrat López Aparicio

https://github.com/SistemasTecTlaxiaco/Academy/wiki/9.1-Diagrama-de-Componentes 

Reporte de diagrama de componentes 
[Diagrama de componentes Reporte.pdf](https://github.com/user-attachments/files/18043926/Diagrama.de.componentes.Reporte.pdf)

**Comment by edgarmauricio123** [comment]
Según la rubrica cumple con todo lo único que le faltan son ilustraciones por lo tanto tiene 27/30

**Comment by josealfredo79** [comment]
bien hecho y revisado..
